### ISSUE TITLE
Disabling World Map Overlay resets after restarting client 

### ISSUE THREAD

**Issue by Lifeaquatic2** [beren12/EnhancedFlightMap#11]
When I unclick the World Map Overlay setting in display options this setting resets back to default each time I log in. I can still disable the setting from the option on the top right corner of my larger map but its annoying to do each time.

**Comment by beren12** [comment]
The world map overlay is a main feature of the addon, if you want it to be a permanent setting I will try to find time, but submitting a patch may be faster.
