### ISSUE TITLE
Config Panel not Working

### ISSUE THREAD

**Issue by meltymon** [beren12/EnhancedFlightMap#14]
when i write in the chat /efm config i got this from bugsack
i use WoW Woltk Classic 3.4.1

23x FrameXML/InterfaceOptionsFrame.lua:430: Usage: InterfaceOptionsFrame_OpenToCategory("categoryName" or panel)
[string "=[C]"]: in function `assert'
[string "@FrameXML/InterfaceOptionsFrame.lua"]:430: in function `InterfaceOptionsFrame_OpenToCategory'
[string "@EnhancedFlightMap/EnhancedFlightMap.lua"]:133: in function `EFM_SlashCommandHandler'
[string "@EnhancedFlightMap/EnhancedFlightMap.lua"]:24: in function `?'
[string "@FrameXML/ChatFrame.lua"]:4938: in function <FrameXML/ChatFrame.lua:4884>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4601: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4637: in function <FrameXML/ChatFrame.lua:4633>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:121_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:121_OnEnterPressed"]:1>

Locals:
(*temporary) = nil
(*temporary) = "Usage: InterfaceOptionsFrame_OpenToCategory("categoryName" or panel)"

and i can also not move the Flighttime Bar and its stuck in Middle of the Screen.

**Comment by perringaiden** [comment]
I've uninstalled for this reason.

**Comment by beren12** [comment]
should be fixed
