### ISSUE TITLE
Error: "Flying to: [Text Timer]"

### ISSUE THREAD

**Issue by LadyEclipse** [beren12/EnhancedFlightMap#15]
This error shows for all new characters that I make.

![Screenshot 2023-11-25 120511](https://github.com/beren12/EnhancedFlightMap/assets/152032168/54151d84-18f5-471d-89be-d8607cc88f9a)

**Comment by LadyEclipse** [comment]
It still works on my old ones, though...  🤔

**Comment by LadyEclipse** [comment]
And it's always up, even when I'm not flying anywhere.

**Comment by RangerDanger84** [comment]
Seeing the same exact issue.  It's a shame because this is a great QoL addon.

**Comment by Meriadin** [comment]
I'm having the same problem.

**Comment by LadyEclipse** [comment]
So, is this addon abandoned, then?

**Comment by zaxlofful** [comment]
Same problem....Had to turn it off entirely

**Comment by beren12** [comment]
should be fixed

**Comment by LadyEclipse** [comment]
Yay!! 😄
