### ISSUE TITLE
Thrallmar-Zangarmarsh errors

### ISSUE THREAD

**Issue by Aneko1** [beren12/EnhancedFlightMap#3]
Hello,

I keep receiving the following error message whenever I use the flight masters in Thrallmar, Swamprat post, or Zabra'jin.

First I receive this one: 

Message: Interface\AddOns\EnhancedFlightMap\nodeinfo.lua:13: attempt to concatenate global 'myContinent' (a nil value)
Time: Mon Jun 28 22:57:40 2021
Count: 1
Stack: Interface\AddOns\EnhancedFlightMap\nodeinfo.lua:13: attempt to concatenate global 'myContinent' (a nil value)
[string "@Interface\AddOns\EnhancedFlightMap\FlightMaster.lua"]:66: in function <Interface\AddOns\EnhancedFlightMap\FlightMaster.lua:10>
[string "=[C]"]: in function `DrawOneHopLines'
[string "@Interface\FrameXML\TaxiFrame.lua"]:119: in function <Interface\FrameXML\TaxiFrame.lua:36>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2100: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1945: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1806: in function <Interface\FrameXML\UIParent.lua:1802>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:2571: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1541: in function <Interface\FrameXML\UIParent.lua:660>

Locals: nodeTargets = <table> {
}
routeList = <table> {
}
continent = "Outland"
usableNodes = <table> {
}
deadNodes = <table> {
}
nodeStyle = 0
(for index) = 1
(for limit) = 7
(for step) = 1
i = 1
nodeName = "Thrallmar, Hellfire Peninsula"
fmX = 0.650000
fmY = 0.500000
nodeType = "REACHABLE"

Then I receive this one 

 Message: Interface\AddOns\EnhancedFlightMap\nodeinfo.lua:201: attempt to index local 'myNode' (a nil value)
Time: Mon Jun 28 23:02:53 2021
Count: 4
Stack: Interface\AddOns\EnhancedFlightMap\nodeinfo.lua:201: attempt to index local 'myNode' (a nil value)

Locals: 

Thanks for your help!

**Comment by beren12** [comment]
Should be fixed but until I nail down another annoying bug can you import all the data from the config screen and see if that stops it?
