### ISSUE TITLE
Data doesn't load on game open

### ISSUE THREAD

**Issue by Sheppito** [beren12/EnhancedFlightMap#4]
Every time I launch the game, the flightpath data doesn't pull automatically. To fix it, I have to enable "Continent Map Overlay" and "World Map Overlay" every time. Mind you, I don't want these to be on during gameplay, because 1. I don't want my map to be cluttered with all the lines of FP's, and 2. I don't want to see flightpaths I haven't discovered myself yet. So afterwards I turn those two settings off. I don't know if the addon is only intended to work if those two settings are on. Here's the error messages:

Date: 2021-09-10 11:21:06
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\EnhancedFlightMap\nodeinfo.lua line 13:
   attempt to concatenate global 'myContinent' (a nil value)
Debug:
   [string "@EnhancedFlightMap\nodeinfo.lua"]:13: EFM_NI_CheckReachable()
   [string "@EnhancedFlightMap\nodeinfo.lua"]:40: EFM_NI_Reachable()
   [string "@EnhancedFlightMap\FlightMaster.lua"]:66:
      EnhancedFlightMap\FlightMaster.lua:10
   [string "=[C]"]: DrawOneHopLines()
   [string "@..\FrameXML\TaxiFrame.lua"]:119:
      ..\FrameXML\TaxiFrame.lua:36
   [string "=[C]"]: Show()
   [string "@Interface_TBC\FrameXML\UIParent.lua"]:2073: SetUIPanel()
   [string "@Interface_TBC\FrameXML\UIParent.lua"]:1918: ShowUIPanel()
   [string "@Interface_TBC\FrameXML\UIParent.lua"]:1779:
      Interface_TBC\FrameXML\UIParent.lua:1775
   [string "=[C]"]: SetAttribute()
   [string "@Interface_TBC\FrameXML\UIParent.lua"]:2544: ShowUIPanel()
   [string "@Interface_TBC\FrameXML\UIParent.lua"]:1517:
      Interface_TBC\FrameXML\UIParent.lua:666
Locals:
myNode = "Kalimdor"
myDebug = false
(*temporary) = <function> defined @Interface\AddOns\EnhancedFlightMap\shared_functions.lua:82
(*temporary) = "Checking if node "
(*temporary) = "Kalimdor"
(*temporary) = " is reachable on continent "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate global 'myContinent' (a nil value)"

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  AtlasLootClassic, vv2.3.2-bcc
  AtlasLootClassicData, vv2.3.2-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.3.2-bcc
  AucAdvanced, v1.13.6717 (SwimmingSeadragon)
  AucFilterBasic, v1.13.6680 (SwimmingSeadragon)
  AucScanData, v1.13.6630 (SwimmingSeadragon)
  AucStatHistogram, v1.13.6681 (SwimmingSeadragon)
  AucStatiLevel, v1.13.6705 (SwimmingSeadragon)
  AucStatPurchased, v1.13.6672 (SwimmingSeadragon)
  AucStatSimple, v1.13.6634 (SwimmingSeadragon)
  AucStatStdDev, v1.13.6635 (SwimmingSeadragon)
  AucUtilFixAH, v1.13.6608 (SwimmingSeadragon)
  AutoDismount, v1.0.6
  BagBrother, v
  Bagnon, v9.1.0
  BeanCounter, v1.13.6682 (SwimmingSeadragon)
  BiSTracker, v5.02
  Enchantrix, v1.13.6708 (SwimmingSeadragon)
  EnchantrixBarker, v1.13.6697 (SwimmingSeadragon)
  EnhancedFlightMap, v3.2.0-TBC-Classic
  Fishbringer, v2.5.2-1
  FiveSecondRule, v1.29
  GoldDelta, v0.0.3-beta
  GoldenMail, v1.2.0
  Informant, v1.13.6684 (SwimmingSeadragon)
  LeatrixPlus, v2.5.54
  Questie, v6.5.1
  QuestXP, v0.6
  Recount, vv2.5.2a
  SimpleDruidMana, v0.5.0
  SimpleItemLevel, v1
  SlideBar, v1.13.6668 (SwimmingSeadragon)
  Stubby, v1.13.6614 (SwimmingSeadragon)
  VendorPrice, v1.4.0
  WeaponSwingTimer, v6.5.1
  WideQuestLog, v
  WideQuestLogLevels, v
  XPTracker, v2.0
  ZoneInfoClassic, v1.0
  BlizRuntimeLib_enUS v2.5.2.20502 <none>
  (ck=55c)

Date: 2021-09-10 11:21:08
ID: 2
Error occured in: Global
Count: 5
Message: ..\AddOns\EnhancedFlightMap\nodeinfo.lua line 201:
   attempt to index local 'myNode' (a nil value)
Debug:
   [string "@EnhancedFlightMap\nodeinfo.lua"]:201: EFM_NI_AddNode_FlightDuration()
   [string "@EnhancedFlightMap\FlightMaster.lua"]:192:
      EnhancedFlightMap\FlightMaster.lua:124
   [string "=[C]"]: TaxiNodeOnButtonEnter()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1
Locals:
nodeName = ""
destNodeName = "Splintertree Post, Ashenvale"
flightDuration = 90
nodeStyle = 0
myNode = nil
(*temporary) = ""
(*temporary) = 0
(*temporary) = nil
(*temporary) = false
(*temporary) = <table> {
 Horde = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to index local 'myNode' (a nil value)"

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  AtlasLootClassic, vv2.3.2-bcc
  AtlasLootClassicData, vv2.3.2-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.3.2-bcc
  AucAdvanced, v1.13.6717 (SwimmingSeadragon)
  AucFilterBasic, v1.13.6680 (SwimmingSeadragon)
  AucScanData, v1.13.6630 (SwimmingSeadragon)
  AucStatHistogram, v1.13.6681 (SwimmingSeadragon)
  AucStatiLevel, v1.13.6705 (SwimmingSeadragon)
  AucStatPurchased, v1.13.6672 (SwimmingSeadragon)
  AucStatSimple, v1.13.6634 (SwimmingSeadragon)
  AucStatStdDev, v1.13.6635 (SwimmingSeadragon)
  AucUtilFixAH, v1.13.6608 (SwimmingSeadragon)
  AutoDismount, v1.0.6
  BagBrother, v
  Bagnon, v9.1.0
  BeanCounter, v1.13.6682 (SwimmingSeadragon)
  BiSTracker, v5.02
  Enchantrix, v1.13.6708 (SwimmingSeadragon)
  EnchantrixBarker, v1.13.6697 (SwimmingSeadragon)
  EnhancedFlightMap, v3.2.0-TBC-Classic
  Fishbringer, v2.5.2-1
  FiveSecondRule, v1.29
  GoldDelta, v0.0.3-beta
  GoldenMail, v1.2.0
  Informant, v1.13.6684 (SwimmingSeadragon)
  LeatrixPlus, v2.5.54
  Questie, v6.5.1
  QuestXP, v0.6
  Recount, vv2.5.2a
  SimpleDruidMana, v0.5.0
  SimpleItemLevel, v1
  SlideBar, v1.13.6668 (SwimmingSeadragon)
  Stubby, v1.13.6614 (SwimmingSeadragon)
  VendorPrice, v1.4.0
  WeaponSwingTimer, v6.5.1
  WideQuestLog, v
  WideQuestLogLevels, v
  XPTracker, v2.0
  ZoneInfoClassic, v1.0
  BlizRuntimeLib_enUS v2.5.2.20502 <none>
  (ck=55c)

Idk why the 2nd addon is posting about Ashenvale. Sometimes it's others, usually it's that one, regardless of if I'm going there (usually not). I've tried preloading data (even though I'd prefer to build the FP's on my own), didn't seem to fix anything. The preload goes away eventually anyways.

In a playthrough, once I turn on and off those two overlays, the addon works fine. But it's annoying having to do that every time. And sometimes it takes a couple flicks to kick in the recorded data. I don't see how any of my other addons could conflict with this one. And again, I'm trying to learn the FP's myself. I'm not sure if that's been "corrupted" yet though, considering I've pre-loaded Horde data 2-3x now with not much permanency it seems. Not sure how to clear recorded data either.

I hope this is an easy fix for you. Thanks again for making this addon, I do enjoy its functionality. All the best to you.

**Comment by beren12** [comment]
Should be fixed by now, let me know if not.
