### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by Ellivoc** [beren12/EnhancedFlightMap#6]
Date: 2022-02-09 09:12:10
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\EnhancedFlightMap\nodeinfo.lua line 201:
   attempt to index local 'myNode' (a nil value)
Debug:
   [string "@TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [string "=[C]"]: ?
   [string "@EnhancedFlightMap\nodeinfo.lua"]:201: EFM_NI_AddNode_FlightDuration()
   [string "@EnhancedFlightMap\Timer.lua"]:37: EFM_Timer_EventFrame_OnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
errMsg = "Interface\AddOns\EnhancedFlightMap\nodeinfo.lua:201: attempt to index local 'myNode' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:609
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

AddOns:
  Swatter, v2.5.6773 (SwimmingSeadragon)
  Altoholic, v2.5.007
  Atlas, vv1.49.05
  AtlasBattlegrounds, vv1.49.00
  AtlasBurningCrusade, vv1.49.00
  AtlasClassicWoW, vv1.49.00
  AtlasDungeonLocs, vv1.49.00
  AtlasTransportation, vv1.49.04
  AtlasLootClassic, vv2.4.1-bcc
  AtlasLootClassicData, vv2.4.1-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.4.1-bcc
  AtlasQuest, v4.12.83
  Attune, v250
  AucAdvanced, v2.5.6733 (SwimmingSeadragon)
  AucFilterBasic, v2.5.6759 (SwimmingSeadragon)
  AucScanData, v2.5.6760 (SwimmingSeadragon)
  AucStatHistogram, v2.5.6761 (SwimmingSeadragon)
  AucStatiLevel, v2.5.6765 (SwimmingSeadragon)
  AucStatPurchased, v2.5.6762 (SwimmingSeadragon)
  AucStatSimple, v2.5.6763 (SwimmingSeadragon)
  AucStatStdDev, v2.5.6764 (SwimmingSeadragon)
  AucUtilFixAH, v2.5.6766 (SwimmingSeadragon)
  Auctionator, v9.1.16
  BagBrother, v
  Bagnon, v9.1.4
  BagnonConfig, v
  BeanCounter, v2.5.6767 (SwimmingSeadragon)
  CharacterStatsTBC, v1.2.4
  ClassicCastbars, vv1.4.4
  ClassicCastbarsOptions, vv1.4.4
  CTBarMod, v9.1.0.6
  CTBottomBar, v9.1.0.6
  CTBuffMod, v9.1.0.3
  CTCore, v9.1.0.3
  CTExpenseHistory, v9.0.5.3
  CTLibrary, v9.1.0.5
  CTMailMod, v9.1.5.1
  CTMapMod, v9.1.0.6
  CTPartyBuffs, v9.1.0.1
  CTRaidAssist, v9.1.0.6
  CTTimer, v9.1.0.3
  CTUnitFrames, v9.1.0.6
  CTViewport, v9.1.0.3
  DataStore, v2.5.006
  DataStoreAgenda, v2.5.006
  DataStoreAuctions, v2.5.006
  DataStoreCharacters, v2.5.006
  DataStoreContainers, v2.5.006
  DataStoreCrafts, v2.5.006
  DataStoreInventory, v2.5.006
  DataStoreMails, v2.5.006
  DataStoreQuests, v2.5.006
  DataStoreReputations, v2.5.006
  DataStoreSpells, v2.5.006
  DataStoreTalents, v2.5.006
  DBMCore, ve74c090
  DBMStatusBarTimers, ve74c090
  DBMVPVEM, vec027d6
  Decursive, v2.7.8.4
  DejaClassicStats, v205r020
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v2.5.6768 (SwimmingSeadragon)
  EnchantrixBarker, v2.5.6769 (SwimmingSeadragon)
  EnhancedFlightMap, v3.2.0-TBC-Classic
  ExtendedCharacterStats, v2.11.1
  FishingBuddy, v0.7.5.5
  GatherMate2, v1.46.1-classic
  GTFO, v4.65.1
  HandyNotes, vv1.6.4
  HealBot, v2.5.3.2
  HealBotData, v2.5.3.2
  HealBoten, v2.5.3.2
  HealBotExtraSkins, v2.5.3.0
  HealBotOptions, v2.5.3.2
  HealBotTips, v2.5.3.2
  Informant, v2.5.6770 (SwimmingSeadragon)
  Mapster, v1.9.5
  OmniCC, v9.1.6
  Pawn, v2.5.31
  Quartz, v3.6.8
  Questie, v6.8.4
  RareScanner, v2.5.3
  Reputable, v1.29-bcc
  Scrap, v9.1.2
  ScrapConfig, v
  ScrapMerchant, v
  SilverDragon, vv20501.0
  SilverDragonBurningCrusade, vv20501.0
  SilverDragonClassic, vv20501.0
  SlideBar, v2.5.6771 (SwimmingSeadragon)
  Stubby, v2.5.6772 (SwimmingSeadragon)
  TellMeWhen, v9.1.2
  TitanClassic, v1.5.0.20503
  TitanClassicAmmo, v1.5.0.20503
  TitanClassicBag, v1.5.0.20503
  TitanClassicClock, v1.5.0.20503
  TitanClassicGold, v1.5.0.20503
  TitanClassicLocation, v1.5.0.20503
  TitanClassicLootType, v1.5.0.20503
  TitanClassicPerformance, v1.5.0.20503
  TitanClassicRegen, v1.5.0.20503
  TitanClassicRepair, v1.5.0.20503
  TitanClassicVolume, v1.5.0.20503
  TitanClassicXP, v1.5.0.20503
  TitanProfessionsMulti, v1.1.2
  TomCats, v2.3.21
  TomTom, vv3.0.3
  TradeSkillMaster, vv4.11.17
  VendorPrice, v1.4.2
  WeakAuras, v3.7.8
  BlizRuntimeLib_enUS v2.5.3.20503 <none>
  (ck=cd2)

**Comment by beren12** [comment]
Should be fixed by now
