### ISSUE TITLE
error when going through dungeon portals

### ISSUE THREAD

**Issue by insectdude1258** [beren12/EnhancedFlightMap#7]
![image](https://user-images.githubusercontent.com/24449926/189344001-71eca8c5-d98b-4255-aa85-0c0b4ac8aae8.png)

38x EnhancedFlightMap\nodeinfo.lua:14: attempt to concatenate local 'myContinent' (a nil value)
[string "@EnhancedFlightMap\nodeinfo.lua"]:14: in function `EFM_NI_CheckReachable'
[string "@EnhancedFlightMap\map.lua"]:226: in function `EFM_Map_DisplayEFMPOIs'
[string "@EnhancedFlightMap\map.lua"]:66: in function <EnhancedFlightMap\map.lua:38>
[string "=[C]"]: in function `OnMapChanged'
[string "@Interface_TBCBlizzard_WorldMap\Blizzard_WorldMap.lua"]:121: in function <...e_TBCBlizzard_WorldMap\Blizzard_WorldMap.lua:120>
[string "=[C]"]: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:39: in function `SetMapID'
[string "@Carbonite\NxMap.lua"]:256: in function `SetMapByID'
[string "@Carbonite\NxMap.lua"]:9450: in function `SetToCurrentZone'
[string "@Carbonite\NxMap.lua"]:4207: in function `UpdateWorld'
[string "@Carbonite\NxMap.lua"]:4313: in function `Update'
[string "@Carbonite\NxMap.lua"]:3956: in function <Carbonite\NxMap.lua:3840>

Locals:
myNode = "Nijel's Point, Desolace"
myDebug = false
myContinent = nil
(*temporary) = <function> defined @EnhancedFlightMap\shared_functions.lua:82
(*temporary) = "Checking if node "
(*temporary) = "Nijel's Point, Desolace"
(*temporary) = " is reachable on continent "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'myContinent' (a nil value)"

**Comment by beren12** [comment]
Pushing an update now, should be fixed. Let me know.

**Comment by insectdude1258** [comment]
> Pushing an update now, should be fixed. Let me know.

the red spam in chat is gone, but im getting this error every few min while in dungeon now

131x EnhancedFlightMap\nodeinfo.lua:14: attempt to concatenate local 'myContinent' (a nil value)
[string "@EnhancedFlightMap\nodeinfo.lua"]:14: in function `EFM_NI_CheckReachable'
[string "@EnhancedFlightMap\map.lua"]:226: in function `EFM_Map_DisplayEFMPOIs'
[string "@EnhancedFlightMap\map.lua"]:66: in function <EnhancedFlightMap\map.lua:38>
[string "=[C]"]: in function `OnMapChanged'
[string "@Interface_TBCBlizzard_WorldMap\Blizzard_WorldMap.lua"]:121: in function <...e_TBCBlizzard_WorldMap\Blizzard_WorldMap.lua:120>
[string "=[C]"]: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:39: in function `SetMapID'
[string "@Carbonite\NxMap.lua"]:256: in function `SetMapByID'
[string "@Carbonite\NxMap.lua"]:9450: in function `SetToCurrentZone'
[string "@Carbonite\NxMap.lua"]:4207: in function `UpdateWorld'
[string "@Carbonite\NxMap.lua"]:4313: in function `Update'
[string "@Carbonite\NxMap.lua"]:3956: in function <Carbonite\NxMap.lua:3840>

Locals:
myNode = "Nijel's Point, Desolace"
myDebug = false
myContinent = nil
(*temporary) = <function> defined @EnhancedFlightMap\shared_functions.lua:82
(*temporary) = "Checking if node "
(*temporary) = "Nijel's Point, Desolace"
(*temporary) = " is reachable on continent "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'myContinent' (a nil value)"

**Comment by beren12** [comment]
should be fixed
