### ISSUE TITLE
Wrong time recording on routes that goes throught portals

### ISSUE THREAD

**Issue by javierhimura** [beren12/EnhancedFlightMap#9]
I have noticed that the recordings on flight routes that pass through portals stop recording the moment the load screen starts.

I talking about flight routes between Blood Elfs starting areas and the rest of Eastern Kingom. Particularly for the route Ironforge -> Quel'danas the addon has recorded only 0:17 seconds, that is the time it takes from taking the flight to be teleported near Quel'danas but the griffon takes more time from there until finally landing.

I am not sure if typing /reload while in flight could also affect the timer, due to trigger a load screen too.

**Comment by javierhimura** [comment]
I have tested /Reload and it does not affect the flight timer. In this case, the timer is not recorded, which is not a big problem compared with recording wrong timers.

**Comment by beren12** [comment]
should be fixed
